### ISSUE TITLE
Developing/testing question

### ISSUE THREAD

**Issue by r002** [AdrianApan/yamde#1]
Hi!  I'd found my way over here from the [reddit article](https://www.reddit.com/r/reactjs/comments/mrojjh/yamde_plug_and_play_markdown_editor_my_first_npm/) that you'd posted a few days ago.  I'm interested in contributing to your package! 😀

Today when I cloned your repo though, I only see that you committed the `/src` files related to your package.  Out of curiosity, how do you actually run and test YAMDE?  Is there separate "test harness" code that you develop/test with but didn't commit?

Of course, I could set up webpack locally, build a dummy "harness" container, and instantiate a YAMDE component from there, but I was just curious about your process?

Thanks for sharing your code though!  I look forward to contributing! 👍

**Comment by AdrianApan** [comment]
Hey,

Thanks for checking in and for considering contributing to this.

This version does not have any testing environment/container attached to it. The way I test the package locally is by using `npm link`:

* in the cloned `yamde` project folder run `npm link`
* to avoid a React conflict with the test project run `npm link ../path/to/your/test/project/node_modules/react`
* navigate to the your test project (I used a barebone CRA project) and run `npm link yamde`
* import and use as per docs (`import Yamde from 'yamde'`)

Perhaps if this gets more traction I might add a testing container, but for now it might be premature given there are other QoL improvements I could potentially tackle first.

Hope this helps.
