### ISSUE TITLE
Remove some options from toolbar

### ISSUE THREAD

**Issue by chauhankiran** [AdrianApan/yamde#2]
In toolbar, currently we have couple of actions such as bold, italic, strike through, etc. is it possible to remove one or two items from the toolbar via config/options?

**Comment by AdrianApan** [comment]
Currently this is not an available option but it would be fairly quick to add as an enhancement so most probably I'll work on it soon. Thanks for the suggestion.

**Comment by AdrianApan** [comment]
@chauhankiran I'm about to merge this enhancement (PR #3) and release it under `v1.6.0`. Once out, feel free to bump your package version to use this new feature.
