### ISSUE TITLE
Feature request: Side-by-side mode

### ISSUE THREAD

**Issue by plushugh** [AdrianApan/yamde#4]
Thanks for the project, I have been using yamde in some of my projects, but I think it would be helpful to have an side-by-side mode as an option so users can edit while having an preview.

**Comment by AdrianApan** [comment]
Hey, thanks for the suggestion - This would be quite an addition given the compact UI I initially went for but definitely something to consider. Depending on my free time, I might dive into this at some point down the line. That being said, contributions are always welcome, if you wanna give this a go of course.
