### ISSUE TITLE
Pass `required` as prop

### ISSUE THREAD

**Issue by joepio** [AdrianApan/yamde#7]
Hi! Thanks for maintaining this.

Currently, the `textarea` always sets a `required` attribute. I think this should be optional, and not be on by default.

https://github.com/AdrianApan/yamde/blob/3ebb898db36e247958dd3931ed4e18f0ae0e9b42/src/Yamde.tsx#L113

**Comment by joepio** [comment]
A workaround by my colleague:

```tsx
  const removeRequiredRef = useCallback(
    (el: HTMLDivElement) => {
      if (!el) {
        return;
      }

      const textArea = el.querySelector('textarea');

      if (!props.required) {
        textArea.removeAttribute('required');
      }
    },
    [props.required],
  );

  return (
    <>
      <InputWrapper>
        <RemoveRequiredWrapper ref={removeRequiredRef}>
          <YamdeStyling>
            <Yamde
              value={value ? value : ''}
              handler={e => setVale(e)}
              theme={darkMode ? 'dark' : 'light'}
              {...props}
            />
          </YamdeStyling>
        </RemoveRequiredWrapper>
```

**Comment by AdrianApan** [comment]
Hey Joep! Love this, great find and great potential workaround! 🚀 Thanks for the PR as well, I left a couple of small comments, let me know your thoughts on those and we can take it from there.
